### ISSUE TITLE
关于index计算

### ISSUE THREAD

**Issue by Liangchengdeye** [cndotaer/dp_decrypt#1]
过程中提到的index=XX/14=9；这个数从哪里来的？还有817怎么计算得到的？

**Comment by oomheap** [comment]
先要找到某个字对应的class，去CSS中找到对应的坐标

**Comment by oomheap** [comment]
.df-1d31 {
    background: -126.0px -817.0px;
}

**Comment by Liangchengdeye** [comment]
> 先要找到某个字对应的类，去CSS中找到对应的坐标

谢谢，我已经解决这个问题了。
